muxinc/next-video

package-lock.json, package.json, src/assets.ts, src/cli/init.ts, src/cli/sync.ts, src/handlers/local-upload.ts, src/main.ts, src/video-handler.ts, src/with-next-video.ts, tests/video-handler.test.ts, tsconfig.json
I originally was going to try and add some default timeouts to handlers, but that turned into a gigantic rabbit hole, so bailing on that for now.
Big thing this PR adds is the ability for sync to pick back up on any existing assets that aren't finished and finish the drill on them.
=> Re sync things

README.md
=> Updating Readme with feedback

package-lock.json, package.json, src/assets.ts, src/cli/init.ts, src/cli/sync.ts, src/handlers/local-upload.ts, src/logger.ts, src/with-next-video.ts
=> more attractive logging

.npmignore, LICENSE, package.json
Act like we've been here before, people.
=> Updates for NPM deployment

README.md, package-lock.json, package.json, src/cli/init.ts, src/with-next-video.ts
Until we can get the squatted package name we're stuck with this namespace.
=> Pin to Chalk 4, update the readme

package-lock.json, src/cli/init.ts, src/cli/lib/json-configs.ts, src/constants.ts, tests/cli/factories/package.dep.json, tests/cli/factories/package.devDep.json, tests/cli/factories/package.none.json, tests/cli/lib/json-configs.test.ts
Be a little more helpful! Now this setup process can start with just `npx @mux/next-video init`.
=> Install stuff

src/cli/lib/next-config.ts, src/main.ts
@heff noticed an issue where things breaking within the handler can put things in a weird state, so let's just catch issues there and at least not die.
@AdamJaggard also noticed that our import codemod was borked for CJS.
=> big old try catch and fix imports

src/cli/init.ts
Based on feedback we may want to prompt that we're correct before running it, but the worst case scenario I could think of is someone accidentally having two lock files and we guess the wrong one.
=> Check for, then use, the existing package manager

package.json
fixes #40 
this change fixed the video type errors for me
=> fix: video-types not found because of exports

package-lock.json, package.json, src/next-video.tsx
fixes #53
this adds a width and height property that can be set on the video component itself if the parent's dimensions are derived from the child.
the more common case will be that the parent container has dimensions and then the video component will be set to 100% width of the parent.
=> fix: better video sizing

README.md, package-lock.json, package.json, src/cli/init.ts, src/constants.ts, tests/factories/package.dep.json, tests/factories/package.devDep.json
new NPM package at https://www.npmjs.com/package/next-video
=> fix: update package name to next-video

package-lock.json, package.json, src/handlers/api-request.ts, src/handlers/local-upload.ts, tests/utils/fake-mux.ts
upgrades the Mux node SDK to a canary release to fix the npx issue and potential yarn git ssh issues
=> fix: Mux node SDK upgrade

src/cli/init.ts
=> fix: yarn add typo

package.json, src/assets.ts, src/cli/lib/json-configs.ts, src/cli/sync.ts, tests/cli/sync.test.ts
=> fix: cleaner CLI watch log output 

src/cli/init.ts, src/components/utils.ts, src/components/video.tsx, src/with-next-video.ts
=> fix: symlink lingering in public folder and added to git

src/cli/init.ts
The init wizard currently ends without telling you what to do next.
@decepulis we may need to think about how this works alongside your addition.
=> Add next step at end of init

src/with-next-video.ts
since we already have `videoConfigDefault`.
=> make `videoConfig` parameter optional

src/components/video.tsx
fixes #76
this adds the class and the style to the container instead of the player.
I think it makes more sense but happy to receive feedback on this.
=> fix: add comp className & style to container

README.md
=> Add provider comparison table to the Readme

src/cli/lib/next-config.ts, src/config.ts, src/with-next-video.ts
- [fix: loading next.config.mjs if needed](https://github.com/muxinc/next-video/pull/124/commits/4ea48402a62a38a4b4c20f8c24183612cab814b6)
- [fix: init output for esm next.config.mjs](https://github.com/muxinc/next-video/pull/124/commits/5434b88b617fac9f40f3f0e5ba6b3b57920a9a5e)
- [fix: webpack dynamic import warning](https://github.com/muxinc/next-video/pull/124/commits/4205120608363ff5f2db1a5967874587aac96016)
=> fix: import related bugs

src/components/utils.ts, src/components/video.tsx
=> fix: add warning for non React comps

src/components/utils.ts, src/components/video.tsx
=> fix: prevent polling of string source m3u8 / mpd

src/components/types.ts, src/components/video.tsx
=> feat: support poster image imports

package-lock.json, package.json
https://github.com/muxinc/mux-node-sdk/releases/tag/v8.0.0
https://github.com/muxinc/elements/releases/tag/%40mux%2Fmux-player-react%402.3.2
=> fix: upgrade Mux dependencies

README.md, src/components/default-player.tsx
https://github.com/muxinc/next-video/discussions/146
=> feat: support slotted poster img (e.g. next/image)

src/cli/sync.ts
=> fix: support Node 16 get files recursively

README.md
readme: https://github.com/luwes/next-video/blob/readme-update/README.md
- [docs: add details / summary to optional sections](https://github.com/muxinc/next-video/pull/215/commits/a2aaa49f6f569e8f6c1affe0c99e8073015b6c13)
- [docs: add BackgroundVideo & tweaks](https://github.com/muxinc/next-video/pull/215/commits/20a009f1eb712da111c322950fe551b4a6d407da)
=> docs: add details / summary to optional sections + BackgroundVideo

package-lock.json
https://github.com/advisories/GHSA-hhhv-q57g-882q
=> fix: jose vulnerability

package-lock.json, package.json, tests/components/video-loader.test.ts, tests/components/video.test.tsx
fix #224
we ran into this issue before, my bad for forgetting to test a CJS next config
=> fix: ESM only import issue chalk v5, use v4

src/cli/sync.ts, src/utils/logger.ts
=> fix: dup sync via watch

examples/default-provider/next-video.mjs, package-lock.json, package.json, src/config.ts, src/providers/mux/provider.ts
=> feat: add `videoQuality` Mux config

README.md
=> docs: add styling section

src/components/players/background-player.tsx
for targettting the native video in shadow dom...
=> fix: set object-fit to cover for background video

src/cli/adopt.ts
When I was testing out the adopt feature a little more I noticed it wasn't pulling in the title from Mux, so added some quick qol stuff to have it grab that for things like filename.
=> feat: use the asset metadata for a default filename
