src/cli/sync.ts

Only call the handler if the asset status is a state where the handler can actually do anything.

Only re-sync existing assets that are not ready or errored. Fixes #28

---

README.md
src/cli/init.ts
src/cli/sync.ts
src/constants.ts
src/next-video.tsx
src/with-next-video.ts

We had one suggestion to call the dir `/videos` to match what similar projects do.
We also had a friction log where multiple levels of directories caused friction in the directory setup process.
While the original design was meant to account for future config files, we're deciding to solve that in a different way in the future.

Change /video/files dir to /videos

---

package-lock.json
package.json
src/cli.ts

Came up as a friction point a couple of times. Since we have to be in our own process, we don't get to rely on Next's sourcing of .env files. ~[dotenv-flow](https://github.com/kerimdzhanov/dotenv-flow) seems to be pretty close to the Next approach, so starting there.~ Nevermind, for now we'll just use [@next/env](https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts) so we can be sure we're following their pattern.
Closes #26.

automatically source .env and .env.local

---

package-lock.json
package.json
src/cli/init.ts
src/cli/lib/json-configs.ts
src/logger.ts
tests/cli/lib/json-configs.test.ts
tests/cli/sync.test.ts

You: "hey I don't understand, why aren't you just reading the JSON file, parsing it, updating it, and then stringifying it back right into that file?"
Wow, so glad you asked. The issue with that is it entirely blows away the formatting of the JSON the user might have had. This might not be a big deal usually, but people have opinions about how they want their configs to look. So if we did the naive approach, we'd end up taking someone's config that looked like this:
```json
{
"includes": ["foo", "bar", "baz"],
"excludes": ["bleep", "bloop", "blap"]
}
```
and turning it into this:
```json
{
"includes": [
"our-new-thing",
"foo", 
"bar", 
"baz"
],
"excludes": [
"bleep", 
"bloop", 
"blap"
]
}
```
Feels like a big time bummer to hand someone a big pile of changes in their config file(s) just …

Moar wizardy: update some tsconfigs

---

src/cli/sync.ts

Init did create a `videos` folder, but it looks like I missed this in the directory name change plural?

Fix default directory name

---

src/next-video.tsx

Our readme's example doesn't have a `controls` prop but our type defines it as required so TS complains using our example. This defaults it to true and makes it optional (should it default to false?).

fix: optional controls prop

---

README.md
package.json

Added the ability for us to automatically determine the package manager and install it, but the explicit step is safer up front for now and gets around at least one friction log stumble.

add explicit installation step back to the readme

---

.github/workflows/cd.yml

uses the script at https://github.com/luwes/wet-run/blob/main/src/release.js
it's similar to https://github.com/muxinc/media-chrome/blob/main/scripts/publish.sh

chore: add CD GH action

---

package.json

worth a shot but not sure if it will have an impact on the "npx without first install" bug
https://github.com/npm/cli/blob/d7265045730555c03b3142c004c7438e9577028c/workspaces/libnpmexec/test/get-bin-from-manifest.js#L5-L16
according to NPM tests the scope should not be included
```js
t.test('extract scope from manifest name with multiple bins', t => {
const bin = getBinFromManifest({
name: '@npmcli/foo',
bin: {
foo: 'foo',
bar: 'bar',
},
})
t.equal(bin, 'foo', 'should pick same name as package')
t.end()
})
```
(also sorry @mmcc, I remember making the case to you it should be the same name)
it seems to pick the command if there is just 1 or if the pkg name is the same

fix: bin name without scope

---

README.md
package-lock.json
package.json
src/assets.ts
src/cli/sync.ts
src/constants.ts
src/handlers/api-request.ts
src/handlers/local-upload.ts
src/handlers/remote-request.ts
src/main.ts
src/next-video.tsx
src/request-handler.ts
src/webpack-loader.ts
src/with-next-video.ts

This PR adds support for creating a Mux clip from a remote source url.
A Next.js API is required in the web app to handle the `/api/video` route.
```js
// pages/api/video/[[...handler]].ts
export { default } from '@mux/next-video/request-handler'
```
```js
// app/page.tsx
import Video from '@mux/next-video';
export default function Home() {
return <Video style={{ width: 640, aspectRatio: 2.4 }} src="https://stream.mux.com/A3VXy02VoUinw01pwyomEO3bHnG4P32xzV7u1j1FSzjNg/high.mp4" />;
}
```
saved in 
```json
// videos/https_stream.mux.com_A3VXy02VoUinw01pwyomEO3bHnG4P32xzV7u1j1FSzjNg_high.mp4.json
{
"status":"ready",  
"originalFilePath": "https://stream.mux.com/A3VXy02VoUinw01pwyomEO3bHnG4P32xzV7u1j1FSzjNg/high.mp4", 
"externalIds":{"assetId":"0102502PiOVxFuSEdNESe7m00wrs00XBARJWZRBlFdTUcGxg" …
```

feat: add (string & import) remote src support 

---

package.json

`repository` was also needed to enable https://docs.npmjs.com/cli/v9/commands/npm-publish#provenance
see failing canary release 
https://github.com/muxinc/next-video/actions/runs/6489362625/job/17623486192

chore: add pkg links, repository, keywords

---

src/cli.ts

this was throwing with a remote video import 
https://github.com/muxinc/next-video/blob/253015f1b4ce39620a680948e983d3edc1e994ed/src/assets.ts#L74-L75

fix: env issue importing remote video source

---

README.md
src/components/default-player.ts
src/components/default-player.tsx
src/components/types.ts
src/components/utils.ts
src/components/video-loader.ts
src/components/video.tsx

fixes #77
This PR adds a new `as` property, lots of reshaping and extracted the provider (Mux) part from the default player (Mux) part. There is a prop called `asset` that is passed to the (custom) Player, this might need some discussion.

feat: support custom player & tidy up

---

src/cli/init.ts

fix: add CLI devscript flag

---

README.md

Had an offline discussion with @luwes and we figured that camelCase is kinda unusual for mp4 filenames. This PR fixes that in our README, as well as addressing two typos

Minor README nits

---

src/components/default-player.tsx

Noticed this issue in next-video-site's [page speed insights](https://pagespeed.web.dev/analysis/https-next-video-dev/kzzh1bjaiu?form_factor=mobile)
Following the example of the [underlying media-chrome-image component's default](https://github.com/muxinc/media-chrome/blob/db3f0f64e5fd6da12f996a9cbff1854bf45803ab/src/js/media-poster-image.js#L32), I propose we add `aria-hidden="true"` to next-video's poster.

Hide poster from screen readers

---

src/components/default-player.tsx

This fixes some bugs with using a custom poster or a custom blurDataURL.
We can only use srcset if using the Mux image API to get the different sizes.
Otherwise set a normal img src attribute.
For the blurDataURL one can only use it when not using a custom poster because it wouldn't match the generated blur hash anymore. Or set both a custom poster and custom blurDataURL that will work too...

fix: poster bugs

---

src/cli/init.ts

Fixes the gitignore exclusion rules as they weren't taking affect. Vercel deployment after a basic setup and video import was failing because the json files were being ignored. Also adds a title to the rules to match nextjs's other sections and a newline at the end.

fix: gitignore generation excluding json files

---

README.md
package-lock.json
package.json
src/assets.ts
src/cli/lib/json-configs.ts
src/cli/sync.ts
src/components/video.tsx
src/config.ts
src/handlers/api-request.ts
src/handlers/local-upload.ts
src/providers/mux.ts
src/providers/providers.ts
src/providers/vercel-blob.ts
src/request-handler.ts
src/utils.ts
src/video-handler.ts
src/with-next-video.ts

requires a `BLOB_READ_WRITE_TOKEN` env variable
with a next.config.js similar to
```js
const { withNextVideo } = require('next-video/process')
/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = withNextVideo(nextConfig, {
provider: 'vercel-blob',
})
```

feat: add Vercel Blob provider

---

src/webpack-loader.ts

fix #107
Error: Cannot create a string longer than 0x1fffffe8 characters

fix: webpack loader ERR_STRING_TOO_LONG

---

src/assets.ts
src/cli.ts
src/cli/sync.ts
src/components/default-player.tsx
src/components/utils.ts
src/components/video.tsx
src/config.ts
src/providers/mux/provider.ts
src/providers/mux/transformer.ts
src/providers/providers.ts
src/providers/transformers.ts
src/providers/vercel-blob/provider.ts
src/providers/vercel-blob/transformer.ts
src/request-handler.ts
src/utils.ts
src/webpack-loader.ts
src/with-next-video.ts
tests/cli/sync.test.ts
tests/utils.test.ts

- this pr updates the asset schema to the schema below.
- `poster` and `sources` are derived data so I didn't add them to the stored state yet.
to generate this derived data, `transformer`'s were added alongside the provider files.
not in the same file as the provider, because the front-end needs to pull this in.
- I tried to add some more logic to assets.ts and re-use it where was possible.
```ts
export interface Asset {
status: 'sourced' | 'pending' | 'uploading' | 'processing' | 'ready' | 'error';
originalFilePath: string;
provider: string;
providerSpecific?: {
[provider: string]: { [key: string]: any }
};
blurDataURL?: string;
poster?: string;
sources?: AssetSource[];
size?: number;
error?: any;
createdAt: number;
updatedAt: number;
// Here for backwards compatibility with older …
```

feat: update schema, add provider key + transform

---

README.md
src/config.ts
src/providers/amazon-s3/provider.ts
src/providers/amazon-s3/transformer.ts
src/providers/providers.ts
src/providers/transformers.ts
src/utils/s3.ts

Amazon made some security changes recently which made the implementation more difficult 
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
it's not 1 to 1 anymore with Backblaze but still very similar.

feat: add Amazon S3 provider

---

package-lock.json
package.json
src/config.ts
src/with-next-video.ts

- [fix: Webpack dynamic import warning better](https://github.com/muxinc/next-video/commit/bf5a5300705112a339304ecf12fe3f74c04722f6)
- [fix: downgrade @aws-sdk/client-s3 to fix bundling](https://github.com/muxinc/next-video/commit/1ff9773b2f85c44393049172b7e816fb2a985d7f)
related issue https://github.com/aws/aws-sdk-js-v3/issues/5435
this happened only when using string video sources so it would use an API endpoint and when bundling or importing the AWS sdk it would throw this 
> TypeError: endpointFunctions_1.endpointFunctions[fn] is not a function
statically imported local or remote video sources worked fine.

fix: bundling related issues 

---

src/components/default-player.tsx

this is needed in any case because when using a custom player we shouldn't be importing Mux player at all

feat: use lazy loading of Mux player

---

src/components/video.tsx

related issue https://github.com/muxinc/next-video/issues/131
related PR https://github.com/muxinc/next-video/pull/79
if a width AND height is set on the container via CSS the internal player should expand to the container and not keep the default aspect-ratio of 16:9 that is set.

fix: set aspect on container, easier override

---

src/assets.ts
src/cli/sync.ts
src/config.ts
src/providers/amazon-s3/provider.ts
src/providers/amazon-s3/transformer.ts
src/providers/backblaze/provider.ts
src/providers/backblaze/transformer.ts
src/providers/vercel-blob/provider.ts
src/request-handler.ts
src/utils/provider.ts
src/utils/utils.ts
src/webpack-loader.ts
src/with-next-video.ts
tests/components/video.test.tsx

fix #149
also fixes a few bugs with reading files in nested folders and creating a file in a nested folder.
this change adds 2 new configurations
```js
/* An optional function to generate the local asset path for remote sources. */
remoteSourceAssetPath?: (url: string) => string;
```
this allows you to change the local folder structure in the configured videos folder for remote sources.
for example you might want to make this 
`/videos/remote/www.dropbox.com_s_dqzkxva260lo7mm_Mad_Max_Cropped.mp4.json` 
instead of the default
`/videos/www.dropbox.com_s_dqzkxva260lo7mm_Mad_Max_Cropped.mp4.json`
or strip the domain and dirname altogether
`/videos/remote/Mad_Max_Cropped.mp4.json`
---
for all the bucket providers (vercel-blob, backblaze, amazon-s3) it adds 
```js
/* An optional function to …
```

feat: custom local remote source folder & custom asset bucket key

---

src/cli/lib/next-config.ts

fix: use posix path in generated JS modules

---

examples/default-provider/next.config.mjs
package-lock.json
package.json

needed a locked version
- @types/react types would not be compatible with Mux elements older React types 
- newer tsx was breaking test coverage
- undici 6 was breaking next.js builds 
I tested the new aws-sdk worked as expected.

fix: upgrade aws-sdk, Mux elements

---

README.md
examples/default-provider/app/custom-player/page.tsx
examples/default-provider/app/custom-player/player.tsx
examples/default-provider/app/sidebar-nav.tsx
examples/default-provider/package-lock.json
examples/default-provider/package.json
src/components/players/background-player.tsx
src/components/types.ts
src/components/video.tsx

fixed a react-player issue in https://github.com/cookpete/react-player/pull/1775

fix: fix custom player types + add react-player example

---

examples/default-provider/app/background-video/page.tsx
examples/default-provider/app/custom-player/page.tsx
src/components/players/background-player.tsx
src/components/video.tsx

the background video was not aligning perfectly going from image to video.
the default video had a small spacing at the bottom of the player.

fix: video dimension bugs, extra spacing

---

examples/default-provider/app/background-video/page.tsx
examples/default-provider/app/globals.css
src/components/players/background-player.tsx

blur image not show before either img or video got dimensions via their url sources.
I also got reminded that we can probably get the aspectRatio from the tiny image on the server and store that.
that way the user doesn't need to manually set it.

fix: sizing issue w/ bg video which made the

---

examples/default-provider/next.config.mjs
src/config.ts

fix: async function as next config

---

README.md

adds a small section how to use next-video without any upload and processing via the `/player` and `/background-player` exports.

docs(readme): add player only section

---

src/assets.ts
src/config.ts
tests/cli/lib/next-config.test.ts
tests/with-next-video.test.ts

This proposal aims to keep next-video fully backward compatible while allowing assets to be saved to a database or sent to an API.
The idea is to make the asset-saving and uploading functions configurable, so developers can choose where to save them. The default configuration will maintain the current behavior of saving to the filesystem.
This is a draft; there are still some tests to fix, but I would appreciate any early feedback.

feat: Allow assets to be saved in different locations

---

src/cli/sync.ts
src/providers/mux/provider.ts

Closes #52 
- Missing Mux credentials now returns a known error, with a link to that specific section of next-video docs
- Enhanced error message when credentials are incorrect (but not empty)
1. If `MUX_TOKEN_ID` or `.env.local` is missing:
2. If `MUX_TOKEN_SECRET` is missing:
3. If creds are incorrect:
- Start a project with no Mux creds, no `.env.local` or with incorrect creds
- Add a video to /videos
- Run `npx next-video sync`

feat: handle missing token errors

---

src/providers/mux/provider.ts
src/utils/queue.ts
tests/cli/sync.test.ts

Closes #309 
- Created a queue that limits the creation of upload URLs to one per second, preventing "Too Many Requests" (429) errors.

fix: add a queue to throttle requests and avoid 429 errors

---

README.md

`mux-video` expects `metadata-video-title` but we document `metadataTitle`, which gets transformed to `metadata-title` which doesn't do anything, leading to null titles in Mux Data.

fix: Correct metadata variable name in docs
